import fs from "node:fs";
import path from "node:path";
import { pathsEqual } from "../installation.js";
import {
  type AutostartBackend,
  type AutostartContext,
  assertLauncherValue,
  launcherFilesExist,
} from "./context.js";
import { readRegistration, registerFile, removeRegistration } from "./files.js";
import {
  readWindowsRegistration,
  setWindowsRegistration,
  windowsSystemPath,
} from "./windows-registry.js";

export function windowsLauncherContents(node: string, entry: string, dataDir: string): Buffer {
  for (const value of [node, entry, dataDir]) {
    assertLauncherValue(value);
    if (value.includes('"')) throw new Error("Windows autostart paths cannot contain quotes");
  }
  // Run expands environment placeholders once. Keeping the paths in their values
  // preserves literal percent signs in names instead of expanding them again.
  const script = [
    "' Sash login launcher; generated by sash auto.",
    "Option Explicit",
    "Dim shell, environment",
    'Set shell = CreateObject("WScript.Shell")',
    'Set environment = shell.Environment("PROCESS")',
    `environment("SASH_HOME") = "${dataDir}"`,
    `environment("SASH_AUTOSTART_NODE") = "${node}"`,
    `environment("SASH_AUTOSTART_ENTRY") = "${entry}"`,
    'shell.Run """%SASH_AUTOSTART_NODE%"" ""%SASH_AUTOSTART_ENTRY%""", 0, False',
    "",
  ].join("\r\n");
  return Buffer.from(`\uFEFF${script}`, "utf16le");
}

export function windowsAutostart(ctx: AutostartContext): AutostartBackend {
  const file = path.join(ctx.controlDir, "start.vbs");
  const launcherCommand = () => {
    const wscript = windowsSystemPath(ctx, "wscript.exe");
    for (const value of [wscript, file]) {
      assertLauncherValue(value);
      if (value.includes('"')) throw new Error("Windows autostart paths cannot contain quotes");
    }
    return `"${wscript}" //B //Nologo "${file}"`;
  };
  const contents = () => windowsLauncherContents(ctx.nodePath, ctx.entryPath, ctx.dataDir);
  return {
    async inspect() {
      const registration = await readWindowsRegistration(ctx);
      if (registration.command === null) return "off";
      const target = parseWindowsLauncher(readRegistration(file));
      if (
        !launcherFilesExist(ctx) ||
        registration.command.toLowerCase() !== launcherCommand().toLowerCase() ||
        !target ||
        !sameTargetPath(target.nodePath, ctx.nodePath) ||
        !sameTargetPath(target.entryPath, ctx.entryPath) ||
        !sameTargetPath(target.dataDir, ctx.dataDir)
      ) {
        return "stale";
      }
      return registration.disabled ? "disabled" : "on";
    },
    async set(enabled) {
      if (enabled) {
        await registerFile(file, contents(), () => setWindowsRegistration(ctx, launcherCommand()));
      } else {
        // Explicit off never depends on a readable/current launcher or an inspection.
        await setWindowsRegistration(ctx, null);
        removeRegistration(file);
      }
    },
  };
}

export interface WindowsLauncherTarget {
  nodePath: string;
  entryPath: string;
  dataDir: string;
}

/** Only accept our complete generated script, never arbitrary executable VBScript. */
export function parseWindowsLauncher(
  contents: Buffer | undefined,
): WindowsLauncherTarget | undefined {
  if (!contents) return undefined;
  const text = contents.toString("utf16le");
  const nodePath = text.match(/environment\("SASH_AUTOSTART_NODE"\) = "([^"\r\n]+)"/)?.[1];
  const entryPath = text.match(/environment\("SASH_AUTOSTART_ENTRY"\) = "([^"\r\n]+)"/)?.[1];
  const dataDir = text.match(/environment\("SASH_HOME"\) = "([^"\r\n]+)"/)?.[1];
  if (!nodePath || !entryPath || !dataDir || ![nodePath, entryPath, dataDir].every(path.isAbsolute))
    return undefined;
  return contents.equals(windowsLauncherContents(nodePath, entryPath, dataDir))
    ? { nodePath, entryPath, dataDir }
    : undefined;
}

function sameTargetPath(left: string, right: string): boolean {
  if (pathsEqual(left, right)) return true;
  try {
    return pathsEqual(fs.realpathSync.native(left), fs.realpathSync.native(right));
  } catch {
    return false;
  }
}
