import {
  RiArrowLeftRightLine,
  RiCheckboxCircleLine,
  RiClipboardLine,
  RiCloseLine,
  RiCodeSSlashLine,
  RiComputerLine,
  RiDashboardLine,
  RiDeleteBin6Line,
  RiDownload2Line,
  RiEditLine,
  RiErrorWarningLine,
  RiEyeLine,
  RiEyeOffLine,
  RiFilter3Line,
  RiFlashlightLine,
  RiGlobalLine,
  RiInformationLine,
  RiLoader2Line,
  RiMoonLine,
  RiPauseLine,
  RiPencilLine,
  RiPlayLine,
  RiQuestionLine,
  RiRefreshLine,
  RiSearchLine,
  RiSettings3Line,
  RiShutDownLine,
  RiSpeedLine,
  RiStackLine,
  RiSunLine,
  RiTerminalBoxLine,
  RiTimerLine,
  RiUpload2Line,
} from "@remixicon/vue";
import type { Component } from "vue";

/** Semantic Sash names mapped to official Remix Icon line components. */
export const iconComponents = {
  alert: RiErrorWarningLine,
  "check-circle": RiCheckboxCircleLine,
  clipboard: RiClipboardLine,
  code: RiCodeSSlashLine,
  download: RiDownload2Line,
  edit: RiEditLine,
  eye: RiEyeLine,
  "eye-off": RiEyeOffLine,
  globe: RiGlobalLine,
  grid: RiDashboardLine,
  info: RiInformationLine,
  layers: RiStackLine,
  "list-filter": RiFilter3Line,
  loader: RiLoader2Line,
  monitor: RiComputerLine,
  moon: RiMoonLine,
  pause: RiPauseLine,
  pencil: RiPencilLine,
  play: RiPlayLine,
  power: RiShutDownLine,
  refresh: RiRefreshLine,
  search: RiSearchLine,
  settings: RiSettings3Line,
  speed: RiSpeedLine,
  sun: RiSunLine,
  swap: RiArrowLeftRightLine,
  terminal: RiTerminalBoxLine,
  timer: RiTimerLine,
  trash: RiDeleteBin6Line,
  upload: RiUpload2Line,
  x: RiCloseLine,
  zap: RiFlashlightLine,
} satisfies Record<string, Component>;

export type IconName = keyof typeof iconComponents;

export function resolveIcon(name: string): Component {
  return iconComponents[name as IconName] ?? RiQuestionLine;
}
